//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolvoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int Id { get; set; }
        public string VinNumber { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
    }
}
